{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_02():\n        \"\"\"我是 test_02 用例描述\"\"\"\n        logging.info(\"用例 test_02 执行完成。。\")\n>       assert False\nE       assert False\n\ntaskOne.py:22: AssertionError"}, "description": "我是 test_02 用例描述", "start": 1626791785854, "stop": 1626791785854, "uuid": "13b9d2bb-0659-4b64-9c2c-0bc576b3560b", "historyId": "c36dabf46c13e290011e6d30f6adb7fe", "testCaseId": "7bd5a8c05bfcbf1d55b23515c2520b1a", "fullName": "taskOne#test_02", "labels": [{"name": "suite", "value": "taskOne"}, {"name": "host", "value": "LAPTOP-CDMV833B"}, {"name": "thread", "value": "20536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "taskOne"}]}